#!/usr/bin/env bash
# NOT AUDITED: This script is part of an internal review workspace. Read before running.
#
# Survey Gno stdlib test coverage vs upstream Go.
# For each Gno stdlib package, list Test/Example funcs locally and upstream at
# go1.25.9, diff by name, and write a markdown report sorted by gap size.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
STDLIBS="$ROOT/gno/gnovm/stdlibs"
GO_TAG="go1.25.9"
CACHE="$HERE/.cache/$GO_TAG"
REPORT="$HERE/report.md"

mkdir -p "$CACHE"

extract_tests() {
    # Print Test*/Example* func names, one per line, sorted unique.
    # Tolerate missing files; emits nothing rather than failing.
    local files=("$@")
    [[ ${#files[@]} -eq 0 ]] && return 0
    grep -hE '^func (Test|Example)[A-Z_][A-Za-z0-9_]*' "${files[@]}" 2>/dev/null \
        | sed -E 's/^func ([A-Za-z0-9_]+).*/\1/' \
        | sort -u
}

fetch_go_tests() {
    # Cache upstream _test.go files for one package. Returns non-zero if the
    # package does not exist upstream (so the caller can skip it).
    local pkg="$1"
    local pkg_cache="$CACHE/$pkg"
    mkdir -p "$pkg_cache"
    if [[ -f "$pkg_cache/.fetched" ]]; then
        return 0
    fi
    local listing
    if ! listing=$(gh api "repos/golang/go/contents/src/$pkg?ref=$GO_TAG" 2>/dev/null); then
        return 1
    fi
    local files
    files=$(jq -r '.[]? | select(.name | endswith("_test.go")) | .name' <<<"$listing") || return 1
    while IFS= read -r f; do
        [[ -z "$f" ]] && continue
        if [[ ! -f "$pkg_cache/$f" ]]; then
            curl -fsSL \
                "https://raw.githubusercontent.com/golang/go/$GO_TAG/src/$pkg/$f" \
                -o "$pkg_cache/$f" || return 1
        fi
    done <<<"$files"
    touch "$pkg_cache/.fetched"
}

# Discover Gno stdlib packages: dirs with non-test .gno files.
mapfile -t PKGS < <(
    cd "$STDLIBS" && \
    find . -name '*.gno' -not -name '*_test.gno' -printf '%h\n' \
        | sed 's|^\./||' \
        | sort -u
)

declare -A GO_COUNT GNO_COUNT MISSING_COUNT MISSING_SAMPLE
SKIPPED=()

for pkg in "${PKGS[@]}"; do
    # Gno-only namespaces: no upstream to compare against.
    case "$pkg" in
        chain|chain/*|sys|sys/*) SKIPPED+=("$pkg (gno-only)"); continue ;;
    esac

    if ! fetch_go_tests "$pkg"; then
        SKIPPED+=("$pkg (no upstream at $GO_TAG)")
        continue
    fi

    pkg_cache="$CACHE/$pkg"
    # shellcheck disable=SC2206
    go_files=($pkg_cache/*_test.go)
    # shellcheck disable=SC2206
    gno_files=($STDLIBS/$pkg/*_test.gno)
    # Guard against unmatched globs.
    [[ -e "${go_files[0]}" ]] || go_files=()
    [[ -e "${gno_files[0]}" ]] || gno_files=()

    go_tests=$(extract_tests "${go_files[@]}")
    gno_tests=$(extract_tests "${gno_files[@]}")

    go_n=$(printf '%s' "$go_tests" | grep -c . || true)
    gno_n=$(printf '%s' "$gno_tests" | grep -c . || true)

    if [[ -z "$go_tests" ]]; then
        # No upstream tests (or only build-tagged files we didn't fetch). Skip.
        SKIPPED+=("$pkg (no upstream tests)")
        continue
    fi

    missing=$(comm -23 <(printf '%s\n' "$go_tests") <(printf '%s\n' "$gno_tests"))
    missing_n=$(printf '%s' "$missing" | grep -c . || true)
    missing_sample=$(printf '%s\n' "$missing" | head -5 | paste -sd, -)

    GO_COUNT[$pkg]=$go_n
    GNO_COUNT[$pkg]=$gno_n
    MISSING_COUNT[$pkg]=$missing_n
    MISSING_SAMPLE[$pkg]=$missing_sample

    printf 'scanned %-28s go=%3d  gno=%3d  missing=%3d\n' \
        "$pkg" "$go_n" "$gno_n" "$missing_n" >&2
done

# Build rows sorted by missing count desc (stable secondary by pkg name).
rows_file=$(mktemp)
trap 'rm -f "$rows_file"' EXIT
for pkg in "${!MISSING_COUNT[@]}"; do
    printf '%05d\t%s\t%d\t%d\t%d\t%s\n' \
        "${MISSING_COUNT[$pkg]}" \
        "$pkg" \
        "${GO_COUNT[$pkg]}" \
        "${GNO_COUNT[$pkg]}" \
        "${MISSING_COUNT[$pkg]}" \
        "${MISSING_SAMPLE[$pkg]}"
done | sort -k1,1rn -k2,2 > "$rows_file"

{
    echo "# Stdlib Test Gap Report"
    echo
    echo "Upstream: \`golang/go@$GO_TAG\`. Generated by [run.sh](run.sh)."
    echo
    echo "Name-level diff of \`func Test*\` / \`func Example*\` between Go's"
    echo "\`src/<pkg>/*_test.go\` and Gno's \`gnovm/stdlibs/<pkg>/*_test.gno\`."
    echo "Subcase-level gaps (inside ported funcs) are not detected."
    echo
    echo "| package | Go tests | Gno tests | missing | sample missing |"
    echo "|---|---:|---:|---:|---|"
    while IFS=$'\t' read -r _ pkg go gno miss sample; do
        echo "| \`$pkg\` | $go | $gno | $miss | $sample |"
    done < "$rows_file"
    echo
    if [[ ${#SKIPPED[@]} -gt 0 ]]; then
        echo "## Skipped"
        echo
        for s in "${SKIPPED[@]}"; do echo "- $s"; done
    fi
} > "$REPORT"

echo "wrote $REPORT" >&2
