#!/usr/bin/env bash
# NOT AUDITED — AI-generated tooling. Review before executing in any privileged context.
#
#
# build-reviews-readme.sh
#
# Regenerates reviews/README.md by scanning reviews/pr/<thousand>xxx/<num>-*/
# and querying gh for each PR's current state. Fast (parallel gh calls) and
# truthful (always pulls live state). Run any time the dir layout changes or
# after a batch of new reviews.
#
# Requirements: gh (authenticated), jq
#
# Usage:
#   ./scripts/build-reviews-readme.sh [-o OUTPUT]

set -euo pipefail

OUTPUT="reviews/README.md"
REPO="gnolang/gno"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -o|--output) OUTPUT="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,15p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

cd "$(git rev-parse --show-toplevel)"

if [[ ! -d reviews/pr ]]; then
  echo "reviews/pr not found" >&2
  exit 1
fi

# Collect (bucket, num, dir) tuples
mapfile -t DIRS < <(find reviews/pr -mindepth 2 -maxdepth 2 -type d | sort)

if [[ ${#DIRS[@]} -eq 0 ]]; then
  echo "no review dirs found under reviews/pr/" >&2
  exit 1
fi

# Fetch PR metadata in parallel into a temp dir (one JSON per PR).
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

fetch_one() {
  local num="$1"
  gh pr view "$num" -R "$REPO" \
    --json number,state,title,mergedAt,closedAt,url,isDraft \
    > "$TMP/$num.json" 2>/dev/null \
    || echo "{\"number\":$num,\"state\":\"UNKNOWN\",\"title\":\"\",\"url\":\"https://github.com/$REPO/pull/$num\"}" > "$TMP/$num.json"
}

PR_NUMS=()
for d in "${DIRS[@]}"; do
  base=$(basename "$d")
  num="${base%%-*}"
  [[ "$num" =~ ^[0-9]+$ ]] || continue
  PR_NUMS+=("$num")
done

echo "Fetching ${#PR_NUMS[@]} PRs from $REPO..." >&2

# Run up to 8 in parallel
JOBS=8
i=0
for num in "${PR_NUMS[@]}"; do
  fetch_one "$num" &
  i=$((i+1))
  if (( i % JOBS == 0 )); then wait; fi
done
wait

# Build markdown
{
  echo "# Reviews"
  echo
  echo "PR reviews of [gnolang/gno](https://github.com/$REPO), bucketed by PR number range. Auto-generated by [\`scripts/build-reviews-readme.sh\`](../scripts/build-reviews-readme.sh) — do not edit by hand."
  echo
  echo "_Last updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
  echo
  echo "Status legend: 🟢 open · 🟡 draft · 🟣 merged · 🔴 closed · ⚪ unknown"
  echo
  echo "## PR reviews"
  echo

  # Group by bucket dir name (newest bucket first)
  for bucket in $(find reviews/pr -mindepth 1 -maxdepth 1 -type d | sort -r); do
    bname=$(basename "$bucket")
    count=$(find "$bucket" -mindepth 1 -maxdepth 1 -type d | wc -l)
    echo "### \`$bname/\` ($count)"
    echo
    echo "| PR | Status | Title | Rounds | Reviewers |"
    echo "|---:|:------:|:------|:------:|:----------|"

    # Sort PR dirs by number desc
    while IFS= read -r d; do
      base=$(basename "$d")
      num="${base%%-*}"
      [[ "$num" =~ ^[0-9]+$ ]] || continue
      meta="$TMP/$num.json"
      [[ -f "$meta" ]] || continue

      state=$(jq -r '.state' "$meta")
      title=$(jq -r '.title' "$meta")
      url=$(jq -r '.url' "$meta")
      isDraft=$(jq -r '.isDraft // false' "$meta")
      [[ -z "$title" ]] && title=$(echo "$base" | sed "s/^${num}-//; s/-/ /g")

      case "$state" in
        OPEN)   icon=$([[ "$isDraft" == "true" ]] && echo "🟡" || echo "🟢") ;;
        MERGED) icon="🟣" ;;
        CLOSED) icon="🔴" ;;
        *)      icon="⚪" ;;
      esac

      # Count review rounds: subdirs matching <n>-<hash>
      rounds=$(find "$d" -mindepth 1 -maxdepth 1 -type d -regextype posix-extended -regex '.*/[0-9]+-[a-f0-9]+' | wc -l)

      # Reviewers: collect <model>_<reviewer>.md basenames across all rounds (unique reviewers)
      # Filename: <model>_<reviewer>[__<tier>].md — strip the optional __<tier>
      # suffix first, then capture the segment after the last underscore.
      reviewers=$(find "$d" -mindepth 2 -maxdepth 2 -type f -name '*.md' \
        | sed -E 's|__[^/]+\.md$|.md|' \
        | sed -E 's|.*_([^/_]+)\.md$|\1|' \
        | sort -u | paste -sd ', ' -)
      [[ -z "$reviewers" ]] && reviewers="—"

      # Escape pipes in title
      safe_title=$(printf '%s' "$title" | sed 's/|/\\|/g')

      rel="${d#reviews/}"
      echo "| [#$num]($url) | $icon | [$safe_title]($rel/) | $rounds | $reviewers |"
    done < <(find "$bucket" -mindepth 1 -maxdepth 1 -type d | sort -t/ -k4 -r)
    echo
  done

  # Security
  if [[ -d reviews/security ]]; then
    sec_count=$(find reviews/security -mindepth 1 -maxdepth 1 -type d | wc -l)
    echo "## Security reports ($sec_count)"
    echo
    echo "HackenProof reports under [\`reviews/security/\`](security/). Status tracked in HackenProof, not here."
    echo
    echo "| ID | Slug |"
    echo "|----|------|"
    find reviews/security -mindepth 1 -maxdepth 1 -type d | sort | while IFS= read -r d; do
      base=$(basename "$d")
      id=$(echo "$base" | grep -oE '^[A-Z]+-[0-9]+' || true)
      [[ -z "$id" ]] && id="$base"
      slug="${base#${id}-}"
      [[ "$slug" == "$base" ]] && slug=""
      echo "| \`$id\` | [$slug](security/$base/) |"
    done
    echo
  fi
} > "$OUTPUT"

echo "wrote $OUTPUT" >&2
